services:
  backend:
    image: hono-docker
    build:
      context: .
    ports:
      - "3000:80"
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "5433:5432"
    # environment:
    #   POSTGRES_USER: batch4
    #   POSTGRES_PASSWORD: prostgres
    env_file:
      - path: .env
        required: true
